websources:
  build: ./images/sources
  volumes:
    - ./site:/usr/src/app

neosources:
  build: ./images/sources
  volumes:
    - ./neo:/usr/src/app

node.sources:
  build: ./images/sources
  volumes:
    - ./neo:/usr/src/app

koa.api.base:
  build: ./images/koa.api
  volumes:
    - ./logs:/logs
    - ./node.libs/pg.logger:/usr/local/lib/node_modules/pg.logger
    - ./node.libs/pg.koa.api:/usr/local/lib/node_modules/pg.koa.api

svc.person:
  build: ./images/koa.api
  volumes:
    - ./svc.person:/usr/src/app
  volumes_from:
    - koa.api.base
  env_file:
    - docker.env
  command: sh -c 'while true; do sleep 10000; done'
  ports:
    - "4000:80"
  links:
    - postgres:postgres
    - neo4j:neo4j

svc.user:
  build: ./images/koa.api
  volumes:
    - ./svc.user:/usr/src/app
  volumes_from:
    - koa.api.base
  env_file:
    - docker.env
  command: sh -c 'while true; do sleep 10000; done'
  ports:
    - "4002:80"
  links:
    - postgres:postgres
    - neo4j:neo4j

svc.web-server:
  build: ./images/luminus.server
  volumes:
    - ./cache/.m2:/root/.m2
    - ./svc.web-server:/usr/src/app
  env_file:
    - docker.env
  command: sh -c 'while true; do sleep 10000; done'
  ports:
    - "4001:3000"
  links:
    - postgres:postgres
    - svc.person:svc.person

server:
  build: ./images/server
  command: sh -c 'while true; do sleep 10000; done'
  volumes:
    - ./cache/.m2:/root/.m2
    - .:/usr/src/root
  volumes_from:
    - websources
  env_file:
    - docker.env
  ports:
    - "3000:3000"
    - "7888:7888"
  links:
    - postgres:postgres
    - neonode:neonode

postgres:
  build: ./images/postgres
  env_file:
    - docker.env
  ports:
    - "5432:5432"

schemup:
  build: ./images/schemup
  links:
    - postgres
  volumes:
    - ./schema:/schema
  working_dir: /schema
  env_file:
    - docker.env

neo4j:
  build: ./images/neo4j
  ports:
    - "7474:7474"
  env_file:
    - docker.env
  environment:
    NEO4J_AUTH: none

frontend:
  build: ./images/frontend
  command: sh -c 'while true; do sleep 10000; done'
  volumes:
    - ./cache/.frontend_npm:/root/.npm
  volumes_from:
    - websources
  env_file:
    - docker.env

neonode:
  build: ./images/neonode
  command: sh -c 'while true; do sleep 10000; done'
  volumes:
    - ./cache/.neonode_npm:/root/.npm
  volumes_from:
    - neosources
  env_file:
    - docker.env
  ports:
    - "3001:3000"
  links:
    - neo4j:neo4j
