# Extend the default docker-compose file to add command for auto run containers
server:
  command: lein with-profile production run

neonode:
  command: node app.js

frontend:
  command: node

svc.models.run:
  command: ["sh", "-c", "node app.js >> /logs/svc.models.run.logs 2>&1"]
