---
- name: install node tools
  sudo: yes
  sudo_user: "{{project_user}}"
  npm: >-
    name={{item}}
    executable=~/.nvm/versions/node/v{{nvm_node_version}}/bin/npm
    global=yes
  with_items:
    - "{{node_apps}}"

- name: install node dependencies
  sudo: yes
  sudo_user: "{{project_user}}"
  command: bash -c ". ~/.nvm/nvm.sh; npm install --no-bin-links"
  args:
    chdir: "{{project_dir}}"
  changed_when: false

- name: run gulp build
  sudo: yes
  sudo_user: "{{project_user}}"
  command: bash -c '. ~/.nvm/nvm.sh; gulp {{env}}'
  args:
    chdir: "{{project_dir}}"
  changed_when: false
