---
- name: update apt-get
  sudo: yes
  apt: update_cache=yes cache_valid_time=43200 # update after 12 hours

- name: create necessary directories
  sudo: yes
  sudo_user: "{{project_user}}"
  file: path={{item}} state=directory
  with_items: out_dirs
