---
- name: install leiningen dependencies
  sudo: yes
  sudo_user: "{{project_user}}"
  command: lein deps chdir={{project_dir}}
  changed_when: False

- name: compile cljs
  sudo: yes
  sudo_user: "{{project_user}}"
  command: lein cljsbuild once production
  args:
    chdir: "{{project_dir}}"
  register: cljs_compile_result
  changed_when: cljs_compile_result.stdout.find('Successfully compiled') != -1
