---
- name: generate docker-compose.yml file
  sudo: yes
  sudo_user: "{{ project_user }}"
  template: >-
    src=templates/docker/{{ item }}.yml
    dest={{ project_dir }}/{{ item }}.yml
  with_items:
    - docker-compose
    - docker-compose.prod

- name: run docker images for web service
  sudo: yes
  command: sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
  args:
    chdir: "{{ project_dir }}"
  register: web_docker_compose_result
  changed_when: False
