---
- name: generate docker-compose.yml file
  sudo: yes
  sudo_user: "{{ project_user }}"
  template: >-
    src=templates/web/docker-compose.yml
    dest={{ project_dir }}/docker-compose.yml

- name: generate docker-compose.prod.yml file
  sudo: yes
  sudo_user: "{{ project_user }}"
  template: >-
    src=templates/web/docker-compose.prod.yml
    dest={{ project_dir }}/docker-compose.prod.yml

- name: run docker images for web service
  sudo: yes
  command: sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
  args:
    chdir: "{{ project_dir }}"
  register: web_docker_compose_result
  changed_when: False
