---
- name: generate db.clj config
  sudo: yes
  sudo_user: "{{project_user}}"
  template: src=templates/db_config.clj dest={{project_dir}}/src/config/db.clj

- name: generate neo4j.clj config
  sudo: yes
  sudo_user: "{{project_user}}"
  template: src=templates/neo4j.clj dest={{project_dir}}/src/config/neo4j.clj

- name: generate system.clj config
  sudo: yes
  sudo_user: "{{project_user}}"
  template: src=templates/system_config.clj dest={{project_dir}}/src/config/system.clj

- name: create logrotate config
  sudo: yes
  template: >-
    src=templates/logrotate
    dest=/etc/logrotate.d/{{service_prefix}}

- name: create server service
  sudo: yes
  notify:
    - restart ring server
  template: >-
    src=templates/ring-server.conf
    dest=/etc/init/{{service_prefix}}-ring-server.conf

- name: generate ferm config file for project
  sudo: yes
  template: >-
    src=templates/ferm-input.conf
    dest=/etc/ferm/input/{{project_name}}.conf
