---
- name: generate db.clj config
  sudo: yes
  sudo_user: "{{project_user}}"
  template: >-
    src=templates/web/db.clj
    dest={{project_dir}}/site/src/config/db.clj

- name: generate neo4j.clj config
  sudo: yes
  sudo_user: "{{project_user}}"
  template: >-
    src=templates/web/neo4j.clj
    dest={{ project_dir }}/site/src/config/neo4j.clj

- name: generate system.clj config
  sudo: yes
  sudo_user: "{{project_user}}"
  template: >-
    src=templates/web/system.clj
    dest={{project_dir}}/site/src/config/system.clj

- name: generate docker-compose.yml file
  sudo: yes
  sudo_user: "{{ project_user }}"
  template: >-
    src=templates/docker/{{ item }}.yml
    dest={{ project_dir }}/{{ item }}.yml
  with_items:
    - docker-compose
    - docker-compose.prod
