---
- name: create scripts for frontend
  template: >-
    src=templates/web/{{ item }}
    dest={{ script_dir }}/{{ item }}
    mode=755
  with_items:
    - frontend_npm_install.sh
    - gulp_prod.sh

- name: install frontend dependencies
  command: ./frontend_npm_install.sh
  args:
    chdir: "{{ script_dir }}"

- name: run gulp build
  command: ./gulp_prod.sh
  args:
    chdir: "{{ script_dir }}"
