---
- name: install gulp dependencies
  sudo: yes
  sudo_user: "{{project_user}}"
  npm: >-
    executable=~/.nvm/v{{nvm_node_version}}/bin/npm
    path={{project_dir}}

- name: run gulp build
  sudo: yes
  sudo_user: "{{project_user}}"
  command: bash -c '. ~/.nvm/nvm.sh; gulp {{env}}'
  args:
    chdir: "{{project_dir}}"
  changed_when: false
