---
- name: update apt-get
  sudo: yes
  apt: update_cache=yes cache_valid_time=43200 # update after 12 hours

- name: create necessary directories
  sudo: yes
  sudo_user: "{{project_user}}"
  file: path={{ item }} state=directory
  with_items: out_dirs

- name: create some aliases
  sudo: yes
  sudo_user: "{{ project_user }}"
  lineinfile: >-
    dest=~/.bashrc
    line="{{ item }}"
  with_items:
    - alias dcb='sudo docker-compose build'
    - alias dcu='sudo docker-compose up -d'
    - alias dck='sudo docker-compose kill'
    - alias dcr='sudo docker-compose rm -f'
    - alias dcp='sudo docker-compose ps'
    - alias aw='{{ script_dir}}/attach_web_server.sh'
    - alias af='{{ script_dir}}/attach_frontend.sh'
