---
- name: create scripts for neonode
  template: >-
    src=templates/neo4j/{{ item }}
    dest={{ script_dir }}/{{ item }}
    mode=755
  with_items:
    - neonode_npm_install.sh

- name: install neonode dependencies
  command: ./neonode_npm_install.sh
  args:
    chdir: "{{ script_dir }}"
