---
- name: create nginx config
  sudo: yes
  template: >-
    src=templates/nginx-site
    dest=/etc/nginx/sites-available/{{ site_name }}
  notify:
    - restart nginx

- name: disable default site
  sudo: yes
  file: >-
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

- name: enable project site
  sudo: yes
  file: >-
    dest=/etc/nginx/sites-enabled/{{ site_name }}
    src=/etc/nginx/sites-available/{{ site_name }}
    state=link
  notify:
    - restart nginx
