---
- name: start postgres container
  command: docker-compose up -d postgres
  args:
    chdir: "{{ project_dir }}"
  changed_when: False

- name: create script for running schemup
  template: >-
    src=templates/schemup/schemup.sh
    dest={{ script_dir }}/schemup.sh
    mode=755

- name: run schemup
  command: ./schemup.sh
  args:
    chdir: "{{ script_dir }}"
  register: schemup_result
  changed_when: schemup_result.stdout.find('Creating') != -1 or schemup_result.stderr.find('Upgrading') != -1
  ignore_errors: True
  until: not schemup_result|failed
  retries: 20
  delay: 10
