---
- name: allow ssh connection
  sudo: yes
  ufw: rule=allow port=ssh

- name: allow http connection
  sudo: yes
  ufw: rule=allow port=80

- name: deny all incoming connection
  sudo: yes
  command: ufw default deny incoming
  changed_when: false

- name: enable ufw
  sudo: yes
  ufw: state=enabled

- name: open some ports for dev environment
  sudo: yes
  ufw: rule=allow port={{ item }}
  with_items:
    - 5432
    - 3000
    - 7888
    - 7474
    - 3001
  when: vagrant_env is defined and vagrant_env
