---
# Initialize for remote hosts
- hosts: vps.truongtx.me
  tasks:
    - include: tasks/vps.yml

# Initialize tasks
- hosts: all
  tasks:
    - include: tasks/init.yml

# Main tasks
- hosts: all
  roles:
    - git
    - nvm
    - postgres
    - wget
    - virtualenv
    - schemup
    - oraclejdk
    - clojure
    - curl
    - neo4j
    - nginx
    - ferm

  tasks:
    - name: install leiningen dependencies
      sudo: yes
      sudo_user: "{{project_user}}"
      command: lein deps chdir={{project_dir}}
      changed_when: False

    - name: compile cljs
      sudo: yes
      sudo_user: "{{project_user}}"
      command: lein cljsbuild once production
      args:
        chdir: "{{project_dir}}"
      register: cljs_compile_result
      changed_when: cljs_compile_result.stdout.find('Successfully compiled') != -1

    - include: tasks/config.yml
    - include: tasks/script.yml
    - include: tasks/nginx.yml
    - include: tasks/frontend.yml

  handlers:
    - name: restart ring server
      sudo: yes
      service: name={{service_prefix}}-ring-server state=restarted

    - name: restart nginx
      sudo: yes
      service: name=nginx state=restarted

    - name: reload ferm
      sudo: yes
      command: ferm /etc/ferm/ferm.conf
