---
# Initialize for remote hosts
- hosts: vps.truongtx.me
  tasks:
    - include: tasks/vps.yml

# Initialize tasks
- hosts: all
  tasks:
    - include: tasks/init.yml

# Main tasks
- hosts: all
  roles:
    - nvm
    - postgres
    # - virtualenv
    # - schemup
    # - oraclejdk
    # - clojure
    # - curl
    # - neo4j
    # - ferm

  tasks:
    - name: install packages
      sudo: yes
      apt: name={{item}}
      with_items:
        - git
        - wget
        - curl
        - nginx

    - include: tasks/clj.yml
    - include: tasks/config.yml
    - include: tasks/script.yml
    - include: tasks/nginx.yml
    - include: tasks/frontend.yml

  handlers:
    - name: restart ring server
      sudo: yes
      service: name={{service_prefix}}-ring-server state=restarted

    - name: restart nginx
      sudo: yes
      service: name=nginx state=restarted

    - name: reload ferm
      sudo: yes
      command: ferm /etc/ferm/ferm.conf
