---
- hosts: all
  roles:
    - apt
    - user
    - git
    - nvm
    - postgres
    - virtualenv
    - schemup
    - java
    - clojure

  tasks:
    # create necessary directory
    - name: create out dirs
      sudo: yes
      sudo_user: "{{project_user}}"
      file: path={{item}} state=directory
      with_items: out_dirs

    - name: generate db.clj config
      sudo: yes
      sudo_user: "{{project_user}}"
      template: src=templates/db_config.clj dest={{project_dir}}/src/genconfig/db.clj

    - name: install leiningen dependencies
      sudo: yes
      sudo_user: "{{project_user}}"
      command: lein run -m core.installer chdir={{project_dir}}
      changed_when: False

    - name: create server script template
      sudo: yes
      sudo_user: "{{project_user}}"
      template: >-
        src=templates/ring-server.sh
        dest={{project_dir}}/scripts/ring-server.sh
        mode=755
        owner={{project_user}}

    - name: create server service
      sudo: yes
      notify:
        - restart ring server
      template: >-
        src=templates/ring-server.conf
        dest=/etc/init/{{service_prefix}}-ring-server.conf

    - name: create logrotate config
      sudo: yes
      template: >-
        src=templates/logrotate
        dest=/etc/logrotate.d/{{service_prefix}}

    - name: compile cljs
      sudo: yes
      sudo_user: "{{project_user}}"
      command: lein cljsbuild once production
      args:
        chdir: "{{project_dir}}"
      register: cljs_compile_result
      changed_when: cljs_compile_result.stdout.find('Successfully compiled') != -1

  handlers:
    - name: restart ring server
      sudo: yes
      service: name={{service_prefix}}-ring-server state=restarted
