---
- hosts: all
  tasks:
    - name: create necessary directories
      file: path={{ item }} state=directory
      with_items: "{{ out_dirs }}"

    - name: create attach script for containers
      template: >-
        src=templates/docker/attach_{{ item }}.sh
        dest={{ script_dir }}/attach_{{ item }}.sh
        mode=755
      with_items:
        - web_server
        - schemup
        - postgres
        - frontend
        - neonode

    - name: build all images
      command: docker-compose build
      args:
        chdir: "{{ project_dir }}"

    - include: tasks/schemup.yml
    - include: tasks/frontend.yml
    - include: tasks/neo4j.yml
    - include: tasks/web.yml

    - name: kill all docker containers
      command: docker-compose stop
      args:
        chdir: "{{ project_dir }}"

    - name: run docker images for web service
      command: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
      args:
        chdir: "{{ project_dir }}"
