---
- hosts: all
  tasks:
    - name: create necessary directories
      file: path={{ item }} state=directory
      with_items: "{{ out_dirs }}"

    - name: build all images
      command: docker-compose build
      args:
        chdir: "{{ project_dir }}"

    - name: run install node dependencies for services
      command: docker-compose run {{ item }} npm install --no-bin-links
      with_items:
        - svc.person
        - svc.user
        - svc.pedigree-relation
        - svc.marriage-relation
        - svc.minor-content
        - svc.image
        - svc.tree
        - frontend
      args:
        chdir: "{{ project_dir }}"

    - name: run install lein dependencies for services
      command: docker-compose run {{ item }} lein deps
      args:
        chdir: "{{ project_dir }}"
      with_items:
        - svc.web

    - name: run schemup
      command: docker-compose run schemup schemup commit
      register: schemup_result
      changed_when: schemup_result.stdout.find('Creating') != -1 or schemup_result.stderr.find('Upgrading') != -1
      ignore_errors: True
      until: not schemup_result|failed
      retries: 20
      delay: 5
      args:
        chdir: "{{ project_dir }}"

    - name: run gulp build
      command: docker-compose run frontend gulp prod
      args:
        chdir: "{{ project_dir }}"

    - name: kill all docker containers
      command: docker-compose stop
      args:
        chdir: "{{ project_dir }}"

    - name: run docker images for web service
      command: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
