---
# Initialize for remote hosts
- hosts: vps.truongtx.me
  roles:
    - git
    - user
  tasks:
    - name: clone the repo
      sudo: yes
      sudo_user: "{{project_user}}"
      git: repo=https://github.com/tmtxt/clojure-pedigree.git dest={{project_dir}}

# Initialize tasks
- hosts: all
  tasks:
    - name: create necessary directories
      sudo: yes
      sudo_user: "{{project_user}}"
      file: path={{item}} state=directory
      with_items: out_dirs

# Main tasks
- hosts: all
  roles:
    - apt
    - user
    - git
    - nvm
    - postgres
    - wget
    - virtualenv
    - schemup
    - oraclejdk
    - clojure
    - curl
    - neo4j
    - nginx

  tasks:
    - name: install leiningen dependencies
      sudo: yes
      sudo_user: "{{project_user}}"
      command: lein deps chdir={{project_dir}}
      changed_when: False

    - name: compile cljs
      sudo: yes
      sudo_user: "{{project_user}}"
      command: lein cljsbuild once production
      args:
        chdir: "{{project_dir}}"
      register: cljs_compile_result
      changed_when: cljs_compile_result.stdout.find('Successfully compiled') != -1

    - include: tasks/config.yml
    - include: tasks/script.yml
    - include: tasks/nginx.yml
    - include: tasks/frontend.yml

  handlers:
    - name: restart ring server
      sudo: yes
      service: name={{service_prefix}}-ring-server state=restarted

    - name: restart nginx
      sudo: yes
      service: name=nginx state=restarted
