---
- hosts: all
  roles:
    - { role: docker, sudo: yes }
  tasks:
    - name: create project user
      user: name={{project_user}} shell=/bin/bash groups=docker append=yes
      sudo: yes

# - hosts: giapha.truongtx.me
#   roles:
#     - ferm
#   tasks:
#     - include: tasks/vps.yml
#     - name: generate ferm config file for project
#       sudo: yes
#       template: >-
#         src=templates/ferm-input.conf
#         dest=/etc/ferm/input/{{project_name}}.conf
#       notify:
#         - reload ferm
#   handlers:
#     - name: reload ferm
#       sudo: yes
#       command: ferm /etc/ferm/ferm.conf

- hosts: all
  tasks:
    - include: tasks/init.yml

- hosts: all
  tasks:
    - name: install packages
      sudo: yes
      apt: name={{item}}
      with_items:
        - git
        - nginx

    - include: tasks/config.yml
    - include: tasks/scripts.yml
    - include: tasks/schemup.yml
    - include: tasks/frontend.yml
    - include: tasks/neo4j.yml
    - include: tasks/web.yml
    - include: tasks/nginx.yml

    - name: kill all docker containers
      sudo: yes
      sudo_user: "{{ project_user }}"
      command: docker-compose stop
      args:
        chdir: "{{ project_dir }}"
      changed_when: False

    - name: run docker images for web service
      sudo: yes
      sudo_user: "{{ project_user }}"
      command: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
      args:
        chdir: "{{ project_dir }}"
      register: web_docker_compose_result
      changed_when: False

  handlers:
    - name: restart nginx
      sudo: yes
      service: name=nginx state=restarted
