---
- hosts: all
  tasks:
    - include: tasks/init.yml

- hosts: all
  # roles:
  #   - { role: docker, sudo: yes }
  tasks:
    - include: tasks/docker-compose.yml
    - include: tasks/config.yml

    - name: run docker images for web service
      sudo: yes
      command: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
      register: web_docker_compose_result
      # changed_when: web_docker_compose_result.stderr.find('Starting') != -1

    - include: tasks/scripts.yml
    - include: tasks/schemup.yml
