---
- hosts: all
  tasks:
    - include: tasks/init.yml

- hosts: all
  roles:
    - { role: docker, sudo: yes }
  tasks:
    - include: tasks/config.yml
    - include: tasks/compose.yml
    - include: tasks/scripts.yml
    - include: tasks/schemup.yml
    - include: tasks/frontend.yml
