---
- hosts: all
  tasks:
    - include: micro-tasks/init.yml

- hosts: all
  roles:
    - { role: docker, sudo: yes }
  tasks:
    - name: add docker group
      sudo: yes
      group: name=docker state=present

    - name: add project user to docker group
      sudo: yes
      user: name={{ project_user }} groups=docker append=yes

    - include: micro-tasks/docker-images.yml
    - include: micro-tasks/docker-run.yml
    - include: micro-tasks/docker-compose.yml
