---
# - hosts: all
#   tasks:
#     - name: update apt-get
#       sudo: yes
#       apt: update_cache=yes cache_valid_time=43200 # update after 12 hours

- hosts: all
  # roles:
  #   - { role: docker, sudo: yes }
  tasks:
    - name: build web server docker image
      sudo: yes
      docker_image: >-
        path="/vagrant/docker/web-server"
        name="app/webserver"
        state="present"
