---
# - hosts: all
#   tasks:
#     - name: update apt-get
#       sudo: yes
#       apt: update_cache=yes cache_valid_time=43200 # update after 12 hours

- hosts: all
  # roles:
  #   - { role: docker, sudo: yes }
  tasks:

    # web server
    - name: build web server docker image
      sudo: yes
      docker_image: >-
        path="{{ project_dir }}/images/web-server"
        name="app/webserver"
        state="build"
      changed_when: False

    - name: build docker image for postgres
      sudo: yes
      docker_image: >-
        path="{{ project_dir }}/images/postgres"
        name="app/postgres"
        state="build"
      changed_when: False
