---
- hosts: all
  tasks:
    - include: micro-tasks/init.yml

- hosts: all
  roles:
    - { role: docker, sudo: yes }
  tasks:
    - include: micro-tasks/docker-compose.yml

    - name: run docker images for web service
      sudo: yes
      command: docker-compose up -d
      args:
        chdir: "{{ project_dir }}/web"
      register: web_docker_compose_result
      # changed_when: web_docker_compose_result.stderr.find('Starting') != -1
