---
- name: generate db.clj config
  sudo: yes
  sudo_user: "{{project_user}}"
  template: >-
    src=templates/web/db.clj
    dest={{project_dir}}/web/site/src/config/db.clj

- name: generate neo4j.clj config
  sudo: yes
  sudo_user: "{{project_user}}"
  template: >-
    src=templates/web/neo4j.clj
    dest={{ project_dir }}/web/site/src/config/neo4j.clj

- name: generate system.clj config
  sudo: yes
  sudo_user: "{{project_user}}"
  template: >-
    src=templates/web/system.clj
    dest={{project_dir}}/web/site/src/config/system.clj
